### ISSUE TITLE
can't download pdf

### ISSUE THREAD

**Issue by mattsblack** [NoMod-Programming/PearsonEbookDownloader#10]
Whenever I try to download this pdf I get this error:

Downloading metadata and eText information...
Traceback (most recent call last):
  File "downloader.py", line 223, in <module>
    main(sys.argv[1])
  File "downloader.py", line 86, in main
    userid=bookData['userid'][0],
KeyError: 'userid'

I don't know how to fix it.

**Comment by NoMod-Programming** [comment]
Hi there @mblack1,Pearson stopped including one of the arguments that had previously been required to download the book, so the downloader didn't work up until just now. I've updated the script on and tested it, and it should work. Please download the updated version from GitHub and let me know if it works or if it still has issues

**Comment by YenLegion** [comment]
Tried the most recent version and am getting.

Me@Me$ python3 downloader.py "https://etext.pearson.com/eplayer/book/7Z3LGD14D7"
Trying to extract bookId from url
Traceback (most recent call last):
  File "downloader.py", line 223, in <module>
    main(sys.argv[1])
  File "downloader.py", line 75, in main
    bookId = bookData["bookid"][0]
KeyError: 'bookid'

Me@Me$ python3 downloader.py 7Z3LGD14D7
Traceback (most recent call last):
  File "downloader.py", line 223, in <module>
    main(sys.argv[1])
  File "downloader.py", line 77, in main
    bookId = int(bookId)
ValueError: invalid literal for int() with base 10: '7Z3LGD14D7'

Does this mean this is a type of book that cannot be downloaded? Thanks.

**Comment by NoMod-Programming** [comment]
Yup, you have one of the newer books that are stored as an epub on Pearson's servers. Those aren't supported by this script, and while I did try reversing the format at one point, I ran into too many issues, and wasn't able to make any progress towards making them downloadable and usable, sadly.

**Comment by NoMod-Programming** [comment]
I've created a new issue for all ETEXT2_PXE-style books. At the moment, they're unsupported because they use a completely different format compared to the original etext system this downloader works with. Closed to keep discussion on these types of books in #12
