### ISSUE TITLE
book id is completely different

### ISSUE THREAD

**Issue by resultsaturday** [NoMod-Programming/PearsonEbookDownloader#11]
I've got this book with the url 
https://etext.pearson.com/eplayer/dashboard/book/H0IM2WJBBP/contents?platforms_id=mastering&b=H0IM2WJBBP&idpName=SMS&contextId=hocking50888&smsUserId=105815258&courseName=Physics+1301/1401:+Fall+2019&tool_consumer_instance_guid=etext2.0&lti_message_type=basic-lti-launch-request&lti_version=LTI-1p0&isPrintPage=true&custom_bookid=H0IM2WJBBP&context_id=hocking50888&custom_course_name=Physics+1301/1401:+Fall+2019&custom_displaycourseid=MPCCNG3535529&custom_smsid=105815258&role=cd73502828457d15655bbd7a63fb0bc8yc&custom_error_url=https%3A%2F%2Fsession.masteringphysics.com%2Fmyct%2FeBookPurchase%3FbookCode%3Dyf15&p=&productModel=ETEXT2_PXE&digitalURN=null&versionURN=null&isDeeplink=true&key=287921559615124163862019&deeplink=true
and when I put in the bookid H0IM2WJBBP, it gives the error 
{
  "status" : "failed",
  "code" : "500",
  "description" : "For input string: \"H0IM2WJBBP\""
}

**Comment by NoMod-Programming** [comment]
I've created a new issue for all ETEXT2_PXE-style books. At the moment, they're unsupported because they use a completely different format compared to the original etext system this downloader works with. Closed to keep discussion on these types of books in #12
