### ISSUE TITLE
Finding book ID

### ISSUE THREAD

**Issue by sundrb** [NoMod-Programming/PearsonEbookDownloader#14]
How to find the book ID?
I couldnt able to find the book ID. Please help me

**Comment by pogocool66** [comment]
Same question.

**Comment by sundrb** [comment]
Instructor's Solutions Manual (Download only) for Supply Chain Management: Strategy, Planning, and Operation, 6th Edition
https://www.pearson.com/us/higher-education/product/Chopra-Instructor-s-Solutions-Manual-Download-only-for-Supply-Chain-Management-Strategy-Planning-and-Operation-6th-Edition/9780133800616.html

Need to download this book :) Please help me

**Comment by LulzRose** [comment]
bumping

**Comment by NoMod-Programming** [comment]
I'm sorry, but unfortunately I can't help with the downloading of specific books. This book doesn't seem to be downloadable by this app regardless, though.
