### ISSUE TITLE
PyPDF2 Not Found

### ISSUE THREAD

**Issue by evilbolt** [NoMod-Programming/PearsonEbookDownloader#2]
![screenshot](https://user-images.githubusercontent.com/20114235/51808461-af4cf200-2259-11e9-8c1b-5abd1bcfd020.png)

After installing python3 and pypdf2, i keep getting this error. I know that pypdf2 is installed and working based upon their test from the repo. Any suggestions?

Random, but you know if that url set in that screenshot will work? This is a last ditch attempt, as it seems the book in this setup is some sorta weird  iframed CSS/HTML5 and not pdfs like in your case.

Cheers

**Comment by NoMod-Programming** [comment]
When you installed PyPDF2, did you use the `pip3` command to install it? Python 2 and 3 can have different modules installed. Also, that URL doesn't seem like it would work with this downloader, since at the moment, it only works with urls that start with `https://etext.pearson.com/eplayer/pdfbook`

**Comment by NoMod-Programming** [comment]
Closed for inactivity. Feel free to re-open if the issue is still relevant, but the script works fine on multiple machines I've tested with, including different operating systems
