### ISSUE TITLE
cannot download pdf

### ISSUE THREAD

**Issue by Raffo24** [NoMod-Programming/PearsonEbookDownloader#5]
error code
Downloading metadata and eText information...
Traceback (most recent call last):
  File "downloader.py", line 217, in <module>
    main(sys.argv[1])
  File "downloader.py", line 88, in main
    pageInfo = pageInfo[0]['pdfPlayerPageInfoTOList']
KeyError: 0

**Comment by IndoIjo** [comment]
I also encountered the same problem :(
any fix to this?

**Comment by NoMod-Programming** [comment]
Hi, what type of URL do your books have? This downloader (at the moment) only works on certain books, an only on books that have numerical IDs.

**Comment by Raffo24** [comment]
This is the link(X assumes any value):
http://view.ebookplus.pearsoncmg.com/ebook/launcheText.do?
bookID::114833
globalBookID::CM30238178
userID::XXXXXX
sessionID::ST-184XXX-Ir0FkMRbOWKXXXXXXXXX
smsUserID::ffffffffXXXXa6868d46f25f1ce7XXXX
uid::201X0X0XXXXXXX::
ubd::201X0X0XXXXXXX
ubsd::201X0X0XXXXXXX
hsid::XXXXX6c67cd6a7XXX2130d55e534XXXX

**Comment by NoMod-Programming** [comment]
The script should work for that book type, and as of the latest commit, you only need the bookId to download the book. Go ahead and give it a try, and let me know if there are any issues, but otherwise this issue will be closed for now.
