### ISSUE TITLE
Hello...help me

### ISSUE THREAD

**Issue by rohsshor** [NoMod-Programming/PearsonEbookDownloader#6]
Could Someone help me to convert a book that I have bought? 
Thank you

**Comment by NoMod-Programming** [comment]
Hi @rohsshor, I'd be happy to walk you through the process of converting the book. What is the format of your eText book? (e.g., what does the book's URL start with?). Also, are you comfortable with any programming languages?

**Comment by rohsshor** [comment]
Hello. I don't know any programming languages, in fact the book that I have bought is on C language for Univerisity Course.
the book's url is the following: http://view.ebookplus.pearsoncmg.com/ebook/launcheText.do?values=scenario::16::languageid::4::global::Y::platform::1116::bookID::98313.

thank you for your time

**Comment by rohsshor** [comment]
> 
> 
> Hi @rohsshor, I'd be happy to walk you through the process of converting the book. What is the format of your eText book? (e.g., what does the book's URL start with?). Also, are you comfortable with any programming languages?

Hello, Could you help me?
Thank you
