### ISSUE TITLE
Empty userid and roletypeid parameters

### ISSUE THREAD

**Issue by TwoLeaves** [NoMod-Programming/PearsonEbookDownloader#8]
The URL I'm given for my eText does not have the userid or roletypeid parameters. Can this script be made to support such links?

I don't log into the Pearson website, but rather click a link through my university portal which opens the "Mastering" platform which then has a link to the eText. I am happy to give more specific information, either here or via email. Thanks.

**Comment by NoMod-Programming** [comment]
Just made the script work without either of those parameters. Could you give it a try again, if you still have access to the book (or the bookId)? If you don't have access to either of those, please send me an email and we can see what we can do about that

**Comment by TwoLeaves** [comment]
Works perfectly with the same URL now. Thanks.

**Comment by NoMod-Programming** [comment]
Awesome, I'm glad it works!
