### ISSUE TITLE
Session ID Error

### ISSUE THREAD

**Issue by sabogalc** [NoMod-Programming/PearsonEbookDownloader#9]
All the books I attempt to download give me this error, am I doing something wrong?
_Downloading metadata and eText information...
Traceback (most recent call last):
  File "downloader.py", line 223, in <module>
    main(sys.argv[1])
  File "downloader.py", line 90, in main
    authkey=bookData['sessionid'][0],
KeyError: 'sessionid'_

**Comment by NoMod-Programming** [comment]
Hi CSab6482, Pearson stopped including one of the arguments that had previously been required to download the book, so the downloader didn't work up until just now. I've updated the script just now and tested it, and it should work. Please download the updated version and let me know if it works or if it still has issues

**Comment by sabogalc** [comment]
It almost works! Downloads pages okay but ultimately ends with

[WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by NoMod-Programming** [comment]
Which stage does that occur during? As it's downloading pages, while it's getting bookmark data, or at some other point? (Aka what's the last printout that the script gives before giving the error?)

**Comment by sabogalc** [comment]
As it’s downloading the pages, and riGht at the end. I have a 1,000 ish
page Physics book and it gets to around page 1,070 and ends with that error

**Comment by sabogalc** [comment]
Downloading book id 20072. Please open an issue on GitHub if this book id
is incorrect.
Downloading metadata and eText information...
Downloading pages to "C:\Users\Carlos\AppData\Local\Temp\tmpcm7ssi95"...
Traceback (most recent call last):
  File "downloader.py", line 223, in <module>
    main(sys.argv[1])
  File "downloader.py", line 124, in main
    threadPool.map(download, pageInfo)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py",
line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py",
line 657, in get
    raise self._value
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py",
line 121, in worker
    result = (True, func(*args, **kwds))
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py",
line 44, in mapstar
    return list(map(*args))
  File "downloader.py", line 120, in download
    urllib.request.urlretrieve(getPageUrl(pdfPage['pdfPath']), savePath)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\urllib\request.py",
line 276, in urlretrieve
    block = fp.read(bs)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 457, in read
    n = self.readinto(b)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 491, in readinto
    return self._readinto_chunked(b)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 591, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 636, in _safe_readinto
    n = self.fp.readinto(mvb)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\socket.py",
line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\ssl.py",
line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\ssl.py",
line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly
closed by the remote host

**Comment by NoMod-Programming** [comment]
In that case, try changing the "40" on line 122 to a smaller number like 20 or even 10. That issue usually occurs when too many requests are made too quickly to Pearson's servers (DDOS protection being triggered by downloading too many pages at the same time too quickly)

**Comment by sabogalc** [comment]
No luck with 20. Trying 10 now, and if not, then 5. Thanks for your help

**Comment by NoMod-Programming** [comment]
What's your internet speed? If it's fast enough (keeping in mind that I've only got 50 Mbps, so 40 was the threshold before I started running into Pearson's DDOS protection) it might even be necessary to add a small delay after downloading each book to simulate a slower connection, otherwise I can't think of what the issue would be that'd cause Pearson's DDOS protection to act up like that.

**Comment by sabogalc** [comment]
2.3 Mbps.. I’ll try switching to another connection

**Comment by sabogalc** [comment]
New error
Downloading book id 20072. Please open an issue on GitHub if this book id
is incorrect.
Downloading metadata and eText information...
Downloading pages to "C:\Users\Carlos\AppData\Local\Temp\tmpze0zljlw"...
Traceback (most recent call last):
  File "downloader.py", line 223, in <module>
    main(sys.argv[1])
  File "downloader.py", line 124, in main
    threadPool.map(download, pageInfo)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py",
line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py",
line 651, in get
    self.wait(timeout)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py",
line 648, in wait
    self._event.wait(timeout)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\threading.py",
line 552, in wait
    signaled = self._cond.wait(timeout)
  File
"C:\Users\Carlos\AppData\Local\Programs\Python\Python37\lib\threading.py",
line 296, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by sabogalc** [comment]
It worked! Thank you so much, I'm looking forward to be able to do my
homework without waiting 10 minutes to get to the page.

**Comment by NoMod-Programming** [comment]
Awesome, glad to hear that! In that case, I'll close the issue, but feel free to re-open it if you experience any issues with your book
